# Generated by Django 5.2.4 on 2025-07-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_facebook_url_author_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish_post', 'Can publish post'), ('can_change_author', 'Can change post author')], 'verbose_name': 'Yazı', 'verbose_name_plural': 'Yazılar'},
        ),
    ]
