# Generated by Django 5.2.4 on 2025-07-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Abonelik Tarihi')),
            ],
            options={
                'verbose_name': 'Bülten Abonesi',
                'verbose_name_plural': 'Bülten Aboneleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('awaiting_approval', 'Onay Bekliyor'), ('published', 'Yayınlandı')], default='draft', max_length=20, verbose_name='Durum'),
        ),
    ]
